# Generated by Django 3.0 on 2021-05-04 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210504_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='title',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='GetLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.FloatField(default=0)),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Leave')),
            ],
        ),
    ]
